version: '3'


services:

  database:
    image: postgres:13.3
    volumes:
    - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
  
  router:
    image: nginx
    # restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./frontend/:/path/to/main/frontend:ro

  mintor:
    build: server/
    command: sh -c 'python3 server.py'



  